version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: app-mysql
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME} 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
  
  redis:
    image: redis:latest
    container_name: app-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data:

networks:
  default:
      name: backend
  